### ISSUE TITLE
AttributeError: error getting next input item from partition source

### ISSUE THREAD

**Issue by lleiding** [bytewax/bytewax#285]
### Bug Description

I'm currently hitting a roadblock with this error (see below): on the one hand there is an attribute error, but this only seems to be raised by the 'error consuming from Kafka topic' error. However, if there's an issue setting/assigning the topic, maybe the attribute already indicates the root cause.

I've already tried different bytewax and Python versions but without effect. Weirdly enough the dataflow worked fine before and there was no change to my codebase that would explain it breaking now. 

In any case I currently have no further idea how to approach this. 
Any feedback is greatly appreciated.

### Python version (`python -V`)

python3.10

### Bytewax version (pip list | grep bytewax)

0.16.0 & 0.16.2

### Operating System version (`uname -morp`)

bytewax/bytewax:latest-python3.10

### Relevant log output

```shell
<timely:work-0> AttributeError: (src/inputs.rs:229:34) error getting next input item from partition source
<timely:work-0> Caused by => AttributeError: '_KafkaSource' object has no attribute 'topic'
<timely:work-0> Traceback (most recent call last):
<timely:work-0>   File "/venv/lib/python3.10/site-packages/bytewax/connectors/kafka.py", line 61, in next
<timely:work-0>     f"error consuming from Kafka topic `{self.topic!r}`: {msg.error()}"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.10/site-packages/bytewax/run.py", line 431, in <module>
    cli_main(**kwargs)
RuntimeError: (src/run.rs:311:17) Worker thread died; look for errors above
Process ended.
```

### Steps to Reproduce

```
kafka_conf = {
    "bootstrap.servers": kafka_bootstrap_servers,
    "group.id": "edg.tagging-service",
    "auto.offset.reset": "latest",
    "sasl.mechanism": "PLAIN",
    "security.protocol": "sasl_ssl",
    "sasl.username": kafka_api_key,
    "sasl.password": kafka_api_secret,
}

registry_conf = {
    "url": schema_registry_url,
    "basic.auth.user.info": schema_registry_api_key + ":" + schema_registry_api_secret,
}

schema_registry_client = SchemaRegistryClient(registry_conf)
keywords_schema = schema_registry_client.get_latest_version(
    f"{input_topic}-value"
).schema.schema_str
tags_schema = schema_registry_client.get_latest_version(
    f"{output_topic}-value"
).schema.schema_str

avro_deserializer = AvroDeserializer(schema_registry_client, keywords_schema)
avro_serializer = AvroSerializer(schema_registry_client, tags_schema)

flow = Dataflow()
topics = [input_topic]
flow.input("inp", KafkaInput(kafka_brokers, topics, add_config=kafka_conf))
flow.inspect(lambda x: logging.info(f"Processing message with key: {x[0]}"))
flow.map(lambda x: deserialize_avro(x, avro_deserializer, input_topic))
flow.filter(lambda x: has_keywords(x, config_version, producer))
flow.map(lambda x: filter_stopwords(x, stopwords, config_version))
flow.map(lambda x: map_keywords(x, tag_map, config_version))
flow.map(lambda x: serialize_avro(x, avro_serializer, output_topic))
flow.output("out", KafkaOutput(kafka_brokers, output_topic, add_config=kafka_conf))
```

**Comment by Psykopear** [comment]
Uh, this is an error with a message from kafka, combined with a bug in our connector, good catch!

Looking at [this line](https://github.com/bytewax/bytewax/blob/1a3338b37585b1cd039d823168bf8dea871a6ba0/pysrc/bytewax/connectors/kafka.py#L61), in case there's an error receiving a message from kafka, we raise an exception with a message. In the message string we try to read from `self.topic`, while the name of the variable if `self._topic`, so a different exception is raised while raising the proper one, hence the weird error you get.

This is fixed in the `main` branch, but I didn't realize the bug was present in the released version. We are going to release `0.17` soon, but I think I'm going to open a PR with the fix for `0.16` too to fix the broken release.

**Comment by lleiding** [comment]
Thanks for the quick response!

Yes, now I see it too. If I'm not mistaken, the bug is actually still present in the `main` branch ([see here](https://github.com/bytewax/bytewax/blob/dcc34226a198829514ad7b211ebd852974b32e07/pysrc/bytewax/connectors/kafka.py#L79)).

What is the timeline on releasing this for `0.17` or `0.16`? Anything I can do to help?

**Comment by Psykopear** [comment]
You are right, I tested it with a different branch I was working on where I included the fix, not on main, but I closed that PR for a new one.

I just opened #289 for the fix in the next release.
We are going to release `0.17` this week, so you won't have to wait for long
